[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
name = "lalrpop-generic-grammar"
version = "0.1.0"

[build-dependencies]
lalrpop = "0.13.1"

[dependencies]
lalrpop-util = "0.13.1"
regex = "0.2.2"
